version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-2"  # 서울 리전
    EKS_CLUSTER_NAME: "group01-autosacling-cluster-01"
    IMAGE_REPO_NAME: "snet-flutter-web"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Flutter 설치
      - echo "Flutter 설치 시작..."
      - git clone https://github.com/flutter/flutter.git /flutter
      - export PATH="$PATH:/flutter/bin"
      - flutter doctor --disable-analytics
      - flutter config --enable-web --no-analytics
      
      # eksctl 설치 (EKS 관리 도구)
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin
      
      # Helm 설치 (패키지 매니저)
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
  pre_build:
    commands:
      # ECR 로그인
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 236528210774.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      # ECR 리포지토리 생성 (없는 경우)
      - aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME || aws ecr create-repository --repository-name $IMAGE_REPO_NAME
      
  build:
    commands:
      # Docker 이미지 빌드 (Flutter 빌드는 Docker 내부에서 처리)
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile.web -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 236528210774.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
  post_build:
    commands:
      # ECR에 이미지 푸시
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 236528210774.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
      # EKS 배포
      - echo Deploying to EKS...
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - echo "Adding CodeBuild role to EKS cluster auth..."
      - eksctl create iamidentitymapping --cluster $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION --arn arn:aws:iam::236528210774:role/codebuild-snet05_group01webbeta01-service-role --group system:masters --username codebuild-service-role || echo "Role mapping already exists"
      
      # AWS Load Balancer Controller 설치
      - echo "Setting up AWS Load Balancer Controller..."
      - eksctl utils associate-iam-oidc-provider --cluster $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION --approve || echo "OIDC provider already exists"
      - eksctl create iamserviceaccount --cluster=$EKS_CLUSTER_NAME --region=$AWS_DEFAULT_REGION --namespace=kube-system --name=aws-load-balancer-controller --role-name "AmazonEKSLoadBalancerControllerRole" --attach-policy-arn=arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess --override-existing-serviceaccounts --approve || echo "ServiceAccount already exists"
      
      # Helm으로 ALB Controller 설치
      - echo "Installing AWS Load Balancer Controller via Helm..."
      - helm repo add eks https://aws.github.io/eks-charts || echo "Helm repo already added"
      - helm repo update
      - helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=$EKS_CLUSTER_NAME --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region=$AWS_DEFAULT_REGION --set vpcId=$(aws eks describe-cluster --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION --query "cluster.resourcesVpcConfig.vpcId" --output text) || echo "ALB Controller already installed"
      
      # ALB Controller가 준비될 때까지 대기
      - echo "Waiting for ALB Controller to be ready..."
      - kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=aws-load-balancer-controller -n kube-system --timeout=300s || echo "ALB Controller pods not found, continuing..."
      
      # 애플리케이션 배포
      - echo "Waiting for kubectl to be ready..."
      - sleep 10
      - kubectl apply -f k8s/deployment.yaml --validate=false
      - kubectl rollout status deployment/snet-news-app --timeout=300s

artifacts:
  files:
    - '**/*'