apiVersion: apps/v1
kind: Deployment
metadata:
  name: snet-news-app
  labels:
    app: snet-news-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snet-news-app
  template:
    metadata:
      labels:
        app: snet-news-app
    spec:
      containers:
      - name: snet-news-app
        image: 236528210774.dkr.ecr.ap-northeast-2.amazonaws.com/snet-flutter-web:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: snet-news-app-service
  labels:
    app: snet-news-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: snet-news-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snet-news-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/load-balancer-name: snet-news-alb
    alb.ingress.kubernetes.io/group.name: snet-news-group
spec:
  ingressClassName: alb
  rules:
  - host: news.snetgroup.com  # 원하는 도메인으로 변경
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snet-news-app-service
            port:
              number: 80